spring.application.name=Payment-Service-Proj

server.port=9092

#Register in eureka server
eureka.client.service-url.default-zone=http://localhost:8762/eureka

#connect to admin server
spring.boot.admin.client.url=http://localhost:8999

#activate all the actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.env.enabled=true
management.endpoint.env.show-values=always

#Circuit breaker properties
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.slowCallRateThreshold=60
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.sliding-window-size=10
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.slowCallDurationThreshold=2s

#Connect with ConfigServer
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=MSForConfigServer

#Oracle properties
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=${dbUser}
spring.datasource.password=${dbPwd}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Data-JPA properies
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


