spring.application.name=Season_Finder_MS
spring.application.instance-id=${spring.application.name}${random.value}
server.port=4042
eureka.client.service-url.default-zone=http://localhost:8761/eureka

