spring.application.name=producer-ms-for-circuit-breaker

#MS Port Number
server.port=9091

# Eureka server url
# Eureka server url
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Circuit breaker properties
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.slowCallRateThreshold=60
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.sliding-window-size=10
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instance.producer-ms-for-circuit-breaker.slowCallDurationThreshold=2s

#Actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always