#Service id
spring.application.name=Shopping-ProducerMS

server.port = 9901
#Eureka server publishing info
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#provide service-id and random number as the instance id
eureka.instance.instance-id=${spring.application.name}:${random.value}

